export const headers = [
  { id: 1, name: "Token", isSort: false },
  { id: 2, name: "Created" },
  { id: 3, name: "Smarts" },
  { id: 4, name: "Cng" },
  { id: 5, name: "S. M." },
  { id: 6, name: "Cng" },
  { id: 7, name: "TXs" },
  { id: 8, name: "Cng" },
  { id: 9, name: "Volume" },
  { id: 10, name: "Cng" },
  { id: 11, name: "Liquidity" },
  { id: 12, name: "MKT Cap" },
  { id: 13, name: "Cng" },
  { id: 14, name: "Holders" },
  { id: 15, name: "Cng" },
  { id: 16, name: "CV/CR/HNP/LB", isSort: false },
  { id: 17, name: "", isSort: false },
];
